---
- hosts: serverx
  vars:
    ansible_password: redhat
    mysqladmin_password: abc
  tasks:
    - name: install dependencies
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - httpd
        - mariadb
        - mariadb-server
        - php
        - php-common
        - php-mysql
        - php-gd
        - php-xml
        - php-mbstring
        - php-mcrypt
        - php-xmlrpc
        - unzip
        - wget

    - name: start system ctl
      service:
        name: "{{ item.name }}"
        state: started
        enabled: "{{ item.enabled }}"
      loop:
        - {name: httpd, enabled: yes }
        - {name: mariadb, enabled: yes }
    
    - name: config firewall
      firewalld:
        permanent: yes
        service: http
        state: enabled
        immediate: yes

    - name: clear exist file if exist
      file: dest=sql_script.sql state=absent

    - name: create sql file script
      file: dest=sql_script.sql state=touch mode=044

    - name: write sql script
      lineinfile:
        path: ./sql_script.sql
        line: "{{ item }}"
      loop:
        - "DELETE FROM mysql.user WHERE User='';"
        - "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost','127.0.0.1', '::1');"
        - "DROP DATABASE IF EXISTS test;"
        - "DELETE FROM mysql.db WHERE Db='test' OR Db='test\_%';"
        - "CREATE DATABASE IF NOT EXISTS wordpress;"
        - "GRANT ALL PRIVILEGES on wordpress.* to 'ansible'@'localhost' identified by 'mypassword';FLUSH PRIVILEGES;"

    - name: use mysql password
      ping:

    - name: Run SQL command
      shell:
        cmd: cat ./sql_script.sql | mysql -uroot -p"{{ mysqladmin_password }}"

    - name: CURL Wordpress
      get_url:
        url: https://wordpress.org/wordpress-5.0.tar.gz
        dest: /home/centos/

    - name: Unarchive Wordpress
      unarchive:
        src: /home/centos/wordpress-5.0.tar.gz
        dest: /var/www/html
        remote_src: yes

    - name: Change the permission of wordpress dependencies
      file:
        path: /var/www/html/wordpress
        owner: apache
        group: apache

    - name: chmod file
      file:
        path: /var/www/html/wordpress
        mode: '0755'

    - name: Create folder
      file:
        state: directory
        path: /var/www/html/wordpress/wp-content/uploads
        recurse: yes

    - name: chown apache
      file:
        path: /var/www/html/wordpress/wp-content/uploads
        group: apache

    - name: move file
      copy:
        src: /var/www/html/wordpress/wp-config-sample.php
        dest: /var/www/html/wordpress/wp-config.php
        remote_src: yes

    - name: replace file
      block:
        - name: replace
          lineinfile:
            path: /var/www/html/wordpress/wp-config.php
            regex: 'database_name_here'
            line: define('DB_NAME', 'wordpress');
        - name: replace
          lineinfile:
            path: /var/www/html/wordpress/wp-config.php
            regex: 'username_here'
            line: define('DB_USER', 'ansible');
        - name: replace
          lineinfile:
            path: /var/www/html/wordpress/wp-config.php
            regex: 'password_here'
            line: define('DB_PASSWORD', 'mypassword');
        - name: replace
          lineinfile:
            path: /var/www/html/wordpress/wp-config.php
            regex: 'DB_HOST'
            line: define('DB_HOST', 'localhost');



